# Project configuration
project_name: "path-integration-rnn"
device: "cpu"  # or "cuda" or "mps" depending on your setup

# Initial position
fixed_start: true #to keep the inital position same across trajectories assign it to True

# Data configuration  
num_trajectories: 2000
batch_size: 1000 #changed from 128
num_workers: 7
train_val_split: 0.8
start_time: 0
end_time: 100
num_time_steps: 1000
mu_speed: 0.2
sigma_speed: 0.5
tau_vel: 1

# Place cell configuration
box_width: 2.2  #deleted arena_L added box_width and box_height
box_height: 2.2
place_cell_rf: 0.12
DoG: true    #to use Difference of Gaussian assign it to True, to use simple Gaussian assign it to False
surround_scale: 2
periodic: false

# Model configuration
input_size: 2
hidden_size: 4096 #changed from 400
output_size: 512 # the number of place cells
alpha: 0.7

# activation: "ReLU"  # PyTorch activation function name
#Commented out "ReLU" since activation needs to be passed as nn.ReLU, not a string

#should we add weight_decay=1e-6?

# Training configuration
learning_rate: 0.0001 #changed from 0.01
max_epochs: 500 
